# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Explorer
tagline:          Never satiated
url:              anjesh.github.io
paginate:         1
baseurl:          /
author:
  name:           Anjesh Tuladhar
  url:            https://twitter.com/anjesh
  email:          anjeshtuladhar@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/anjesh/anjesh.github.io

pages_list:       
  Home: '/'
  About: '/about'
  Archive: '/archive'